# Generated by Django 3.2.5 on 2021-08-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_educations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='desc',
            field=models.TextField(max_length=50, verbose_name='توضیحات'),
        ),
    ]
