# Generated by Django 3.2.5 on 2021-08-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_educations', '0002_alter_education_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='desc',
            field=models.TextField(verbose_name='توضیحات'),
        ),
    ]
