# Generated by Django 3.2.5 on 2021-07-30 10:47

from django.db import migrations, models
import site_admin_informations.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin_informations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininformation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=site_admin_informations.models.upload_image_path, verbose_name='عکس پروفایل'),
        ),
    ]
