# Generated by Django 3.2.5 on 2021-08-01 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin_informations', '0003_adminskill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminSkill',
        ),
    ]
