# Generated by Django 3.2.5 on 2021-08-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin_informations', '0004_delete_adminskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininformation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
    ]
