# Generated by Django 3.2.5 on 2021-08-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_css', models.CharField(max_length=50, verbose_name='لوگو')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('desc', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'سرویس ها',
                'verbose_name_plural': 'سرویس ها',
            },
        ),
    ]
