# Generated by Django 3.2.5 on 2021-07-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='code | design')),
                ('skill_name', models.CharField(max_length=150, verbose_name='نام مهارت')),
                ('percent', models.IntegerField(verbose_name='درصد داشتن مهارت')),
            ],
            options={
                'verbose_name': 'مهارت ادمین',
                'verbose_name_plural': 'مهارت های ادمین',
            },
        ),
    ]
