# Generated by Django 3.2.5 on 2021-08-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='سال آموزش')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دوره یا اموزش')),
                ('address', models.CharField(max_length=50, verbose_name='محل گذراندن دوره یا آموزش')),
                ('desc', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'تجربه های کاری',
                'verbose_name_plural': 'تجربه های کاری',
            },
        ),
    ]
