# Generated by Django 3.2.5 on 2021-08-01 13:00

from django.db import migrations, models
import site_members.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to=site_members.models.upload_image_path, verbose_name='عکس')),
                ('name', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'اعضا تیم',
                'verbose_name_plural': 'اعضا تیم',
            },
        ),
    ]
